### ISSUE TITLE
No falsey non empty strings checking

### ISSUE THREAD

**Issue by diegoaguilar** [jonschlinkert/falsey#3]
Right know `isFalse('       ')` returns `false`, IMHO that's wrong, as falsey might be used for simple data validation, this may be kind of unwated behaviour, opinions?

**Comment by jonschlinkert** [comment]
this lib checks string values against a [curated (or custom) list](https://github.com/jonschlinkert/falsey#special-cases) of "falsey" words. I could expose the built-in list as a property so users can concat custom values to it, like `' '`? would that help?

**Comment by doowb** [comment]
@diegoaguilar I think that if you were to use this for validation checking, then you could do `isFalse(val.trim())`. This is mainly because you might have other criteria on how you want the string to be trimmed before passing it into `isFalse`.

I also exposed the list of `keywords` so you can add your values like this:

```js
// new list
isFalse(' ', isFalse.keywords.concat([' ']);

// modify list
isFalse.keywords.push(' ');
isFlase(' ');
```
